
local games = {
	{ -- 1
		class = "slot",
		alias = "novomatic/dolphinspearl",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 5,
		fsr = 0, gain = 0,
	},
	{ -- 2
		class = "slot",
		alias = "novomatic/columbus",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 9,
		fsr = 0, gain = 0,
	},
	{ -- 3
		class = "slot",
		alias = "novomatic/bananasgobahamas",
		gid = 0,
		changesbl = true,
		bet = 5, sln = 5,
		fsr = 0, gain = 0,
	},
	{ -- 4
		class = "slot",
		alias = "novomatic/sizzlinghot",
		gid = 0,
		changesbl = false,
		bet = 1, sln = 0,
		fsr = 0, gain = 0,
	},
	{ -- 5
		class = "slot",
		alias = "megajack/slotopol",
		gid = 0,
		changesbl = true,
		bet = 0.2, sln = 21,
		fsr = 0, gain = 0,
	},
	{ -- 6
		class = "slot",
		alias = "megajack/slotopoldeluxe",
		gid = 0,
		changesbl = false,
		bet = 0.5, sln = 9,
		fsr = 0, gain = 0,
	},
	{ -- 7
		class = "slot",
		alias = "novomatic/plentyontwenty",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 0,
		fsr = 0, gain = 0,
	},
	{ -- 8
		class = "slot",
		alias = "novomatic/ultrahot",
		gid = 0,
		changesbl = false,
		bet = 5, sln = 0,
		fsr = 0, gain = 0,
	},
	{ -- 9
		class = "slot",
		alias = "novomatic/katana",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 0,
		fsr = 0, gain = 0,
	},
	{ -- 10
		class = "keno",
		alias = "aristocrat/americankeno",
		gid = 0,
		bet = 1, ssn = 6,
	},
	{ -- 11
		class = "slot",
		alias = "betsoft/2millionbc",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 10,
		fsr = 0, gain = 0,
	},
	{ -- 12
		class = "slot",
		alias = "playngo/firejoker",
		gid = 0,
		changesbl = false,
		bet = 2, sln = 0,
		fsr = 0, gain = 0,
	},
	{ -- 13
		class = "slot",
		alias = "novomatic/kingofcards",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 5,
		fsr = 0, gain = 0,
	},
	{ -- 14
		class = "slot",
		alias = "novomatic/attila",
		gid = 0,
		changesbl = true,
		bet = 10, sln = 3,
		fsr = 0, gain = 0,
	},
	{ -- 15
		class = "slot",
		alias = "playngo/fortuneteller",
		gid = 0,
		changesbl = true,
		bet = 1, sln = 0,
		fsr = 0, gain = 0,
	},
}
local gamenum = {1, 1, 1, 1, 1, 2, 2, 3, 4, 5, 10, 15}

return games, gamenum
